"""Add permissions column to users

Revision ID: 155929fad48f
Revises: e142a1eddeff
Create Date: 2026-07-01 17:57:02.183188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '155929fad48f'
down_revision: Union[str, None] = 'e142a1eddeff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('purchases_branch_id_foreign'), 'purchases', type_='foreignkey')
    op.drop_constraint(op.f('purchases_supplier_id_foreign'), 'purchases', type_='foreignkey')
    op.drop_constraint(op.f('purchases_user_id_foreign'), 'purchases', type_='foreignkey')
    op.create_foreign_key(None, 'purchases', 'branches', ['branch_id'], ['id'])
    op.create_foreign_key(None, 'purchases', 'suppliers', ['supplier_id'], ['id'])
    op.create_foreign_key(None, 'purchases', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('permissions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'permissions')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.drop_constraint(None, 'purchases', type_='foreignkey')
    op.create_foreign_key(op.f('purchases_user_id_foreign'), 'purchases', 'users', ['user_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('purchases_supplier_id_foreign'), 'purchases', 'suppliers', ['supplier_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('purchases_branch_id_foreign'), 'purchases', 'branches', ['branch_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###
