"""sync_with_ondelete

Revision ID: f8c9d5a43223
Revises: 20b5665a6da6
Create Date: 2026-06-03 04:14:55.794106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f8c9d5a43223'
down_revision: Union[str, None] = '20b5665a6da6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('branch_product_branch_id_product_id_unique'), 'branch_product', type_='unique')
    op.drop_constraint(op.f('brands_slug_unique'), 'brands', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('brands_slug_unique'), 'brands', ['slug'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('branch_product_branch_id_product_id_unique'), 'branch_product', ['branch_id', 'product_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
